import prisma from '../config/prisma';
import { executiveDashboard } from './metrics/analyticsService';
import { runBusinessInsights } from './businessInsightService';
import { buildForecasts } from './metrics/analyticsService';

export async function sendWeeklyExecutiveBrief(organizationId: string) {
  const org = await prisma.organization.findUniqueOrThrow({
    where: { id: organizationId },
    include: {
      users: { where: { role: { in: ['OWNER', 'ADMIN'] }, isActive: true } },
    },
  });
  const dash = await executiveDashboard(organizationId);
  const openRecs = await prisma.recommendation.findMany({
    where: { organizationId, status: 'OPEN' },
    orderBy: { createdAt: 'desc' },
    take: 5,
  });

  const subject = `Weekly Executive Brief — ${org.displayName || org.name}`;
  const html = `
    <h1>${subject}</h1>
    <p>Active students: <strong>${dash.enrolment.activeStudents}</strong></p>
    <p>Month expenses: <strong>$${(dash.expenses.monthExpenseCents / 100).toFixed(2)}</strong></p>
    <p>Cash net monthly outlook: <strong>$${(dash.cash.netMonthlyCents / 100).toFixed(2)}</strong></p>
    <p>Staffing savings opportunity this week: <strong>$${(dash.staffing.estimatedSavingsCents / 100).toFixed(2)}</strong></p>
    <h2>Open Actions</h2>
    <ul>
      ${openRecs.map((r) => `<li>${r.title}</li>`).join('') || '<li>None</li>'}
    </ul>
    <p style="font-size:14px;color:#555">Generated by Business Advisor. Open the app for drill-down evidence.</p>
  `;

  const apiKey = process.env.BREVO_API_KEY;
  const senderEmail = process.env.BREVO_SENDER_EMAIL || 'noreply@businessadvisor.app';
  const senderName = process.env.BREVO_SENDER_NAME || 'Business Advisor';

  if (!apiKey) {
    console.log(`[brief:dry-run] ${subject} -> ${org.users.map((u) => u.email).join(', ')}`);
    return { sent: false, dryRun: true, subject };
  }

  for (const user of org.users) {
    await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'api-key': apiKey,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({
        sender: { email: senderEmail, name: senderName },
        to: [{ email: user.email, name: `${user.firstName} ${user.lastName}` }],
        subject,
        htmlContent: html,
      }),
    });
  }

  return { sent: true, dryRun: false, subject, recipients: org.users.length };
}

export async function runDailyAnalysisForOrg(organizationId: string) {
  await buildForecasts(organizationId);
  return runBusinessInsights(organizationId);
}

export async function runDailyAnalysisAllOrgs() {
  const orgs = await prisma.organization.findMany({
    where: { status: 'ACTIVE' },
    select: { id: true, slug: true },
  });
  const results = [];
  for (const org of orgs) {
    try {
      const r = await runDailyAnalysisForOrg(org.id);
      results.push({ organizationId: org.id, slug: org.slug, ok: true, ...r });
    } catch (err) {
      console.error(`Daily analysis failed for ${org.slug}`, err);
      results.push({
        organizationId: org.id,
        slug: org.slug,
        ok: false,
        error: err instanceof Error ? err.message : 'failed',
      });
    }
  }
  return results;
}

export async function runWeeklyBriefsAllOrgs() {
  const orgs = await prisma.organization.findMany({
    where: { status: 'ACTIVE' },
    select: { id: true, slug: true },
  });
  const results = [];
  for (const org of orgs) {
    try {
      const r = await sendWeeklyExecutiveBrief(org.id);
      results.push({ organizationId: org.id, slug: org.slug, ok: true, ...r });
    } catch (err) {
      console.error(`Weekly brief failed for ${org.slug}`, err);
      results.push({
        organizationId: org.id,
        slug: org.slug,
        ok: false,
        error: err instanceof Error ? err.message : 'failed',
      });
    }
  }
  return results;
}
