import prisma from '../config/prisma';
import { executiveDashboard } from './metrics/analyticsService';
import { runBusinessInsights } from './businessInsightService';
import { buildForecasts } from './metrics/analyticsService';
import { impactSummary } from './impactService';
import { runImpactVerificationForOrg } from './impactVerificationService';
import { ADVICE_DISCLAIMER } from '../config/legal';

function dollars(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

export async function sendWeeklyExecutiveBrief(organizationId: string) {
  const org = await prisma.organization.findUniqueOrThrow({
    where: { id: organizationId },
    include: {
      users: { where: { role: { in: ['OWNER', 'ADMIN'] }, isActive: true } },
    },
  });
  const dash = await executiveDashboard(organizationId);
  const impact = await impactSummary(organizationId);
  const openRecs = await prisma.recommendation.findMany({
    where: { organizationId, status: 'OPEN' },
    orderBy: { createdAt: 'desc' },
    take: 5,
  });

  const impactLines: string[] = [];
  if (impact.verified.totalCents > 0) {
    impactLines.push(
      `<p>Nonso's verified impact to date: <strong>${dollars(impact.verified.savedCents)} saved · ${dollars(impact.verified.earnedCents)} earned</strong> across ${impact.verified.actionCount} completed action${impact.verified.actionCount === 1 ? '' : 's'}.</p>`
    );
    if (impact.thisMonth.totalCents > 0) {
      impactLines.push(
        `<p>This month: <strong>${dollars(impact.thisMonth.totalCents)}</strong> in verified impact.</p>`
      );
    }
  } else {
    impactLines.push(
      '<p>No verified impact from Nonso yet. Complete actions in the Action Centre and confirm their results to build your impact ledger.</p>'
    );
  }
  if (impact.awaitingConfirmationCount > 0) {
    impactLines.push(
      `<p>${impact.awaitingConfirmationCount} completed action${impact.awaitingConfirmationCount === 1 ? ' is' : 's are'} awaiting your impact confirmation in the Action Centre.</p>`
    );
  }
  if (impact.pipelineExpectedCents > 0) {
    impactLines.push(
      `<p>Open action pipeline: <strong>${dollars(impact.pipelineExpectedCents)}</strong> in estimated impact across ${impact.pipelineCount} action${impact.pipelineCount === 1 ? '' : 's'}.</p>`
    );
  }

  const subject = `Weekly Executive Brief — ${org.displayName || org.name}`;
  const html = `
    <h1>${subject}</h1>
    <h2>Nonso's Impact</h2>
    ${impactLines.join('\n    ')}
    <h2>This Week</h2>
    <p>Active students: <strong>${dash.enrolment.activeStudents}</strong></p>
    <p>Month expenses: <strong>$${(dash.expenses.monthExpenseCents / 100).toFixed(2)}</strong></p>
    <p>Cash net monthly outlook: <strong>$${(dash.cash.netMonthlyCents / 100).toFixed(2)}</strong></p>
    <p>Staffing savings opportunity this week: <strong>$${(dash.staffing.estimatedSavingsCents / 100).toFixed(2)}</strong></p>
    <h2>Open Actions</h2>
    <ul>
      ${openRecs.map((r) => `<li>${r.title}</li>`).join('') || '<li>None</li>'}
    </ul>
    <p style="font-size:14px;color:#555">Generated by Business Advisor. Open the app for drill-down evidence.</p>
    <p style="font-size:14px;color:#555">${ADVICE_DISCLAIMER}</p>
  `;

  const apiKey = process.env.BREVO_API_KEY;
  const senderEmail = process.env.BREVO_SENDER_EMAIL || 'noreply@businessadvisor.app';
  const senderName = process.env.BREVO_SENDER_NAME || 'Business Advisor';

  if (!apiKey) {
    console.log(`[brief:dry-run] ${subject} -> ${org.users.map((u) => u.email).join(', ')}`);
    return { sent: false, dryRun: true, subject };
  }

  for (const user of org.users) {
    await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'api-key': apiKey,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({
        sender: { email: senderEmail, name: senderName },
        to: [{ email: user.email, name: `${user.firstName} ${user.lastName}` }],
        subject,
        htmlContent: html,
      }),
    });
  }

  return { sent: true, dryRun: false, subject, recipients: org.users.length };
}

export async function runDailyAnalysisForOrg(organizationId: string) {
  await buildForecasts(organizationId);
  const insights = await runBusinessInsights(organizationId);
  const impactVerification = await runImpactVerificationForOrg(organizationId);
  return { ...insights, impactVerification };
}

export async function runDailyAnalysisAllOrgs() {
  const orgs = await prisma.organization.findMany({
    where: { status: 'ACTIVE' },
    select: { id: true, slug: true },
  });
  const results = [];
  for (const org of orgs) {
    try {
      const r = await runDailyAnalysisForOrg(org.id);
      results.push({ organizationId: org.id, slug: org.slug, ok: true, ...r });
    } catch (err) {
      console.error(`Daily analysis failed for ${org.slug}`, err);
      results.push({
        organizationId: org.id,
        slug: org.slug,
        ok: false,
        error: err instanceof Error ? err.message : 'failed',
      });
    }
  }
  return results;
}

export async function runWeeklyBriefsAllOrgs() {
  const orgs = await prisma.organization.findMany({
    where: { status: 'ACTIVE' },
    select: { id: true, slug: true },
  });
  const results = [];
  for (const org of orgs) {
    try {
      const r = await sendWeeklyExecutiveBrief(org.id);
      results.push({ organizationId: org.id, slug: org.slug, ok: true, ...r });
    } catch (err) {
      console.error(`Weekly brief failed for ${org.slug}`, err);
      results.push({
        organizationId: org.id,
        slug: org.slug,
        ok: false,
        error: err instanceof Error ? err.message : 'failed',
      });
    }
  }
  return results;
}
